"""Initial migration

Revision ID: b7a56b3f0321
Revises: 
Create Date: 2024-06-11 08:54:00.053410

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7a56b3f0321'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atletas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('centro_treinamento', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atletas_cpf'), 'atletas', ['cpf'], unique=True)
    op.create_index(op.f('ix_atletas_id'), 'atletas', ['id'], unique=False)
    op.create_index(op.f('ix_atletas_nome'), 'atletas', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atletas_nome'), table_name='atletas')
    op.drop_index(op.f('ix_atletas_id'), table_name='atletas')
    op.drop_index(op.f('ix_atletas_cpf'), table_name='atletas')
    op.drop_table('atletas')
    # ### end Alembic commands ###
